### ISSUE TITLE
Questions regarding this project?

### ISSUE THREAD

**Issue by Joe23232** [matklad/xshell#22]
So I have some questions regarding this project:
1. Am I legally allowed to use this crate and close source my source code (not that I am planning to do this)?
2. Would it run the same on Linux and Windows?
3. Does this actually run shell scripts or is it all native?
4. Say if I wanted to delete all the file names except one specific file name, what would exactly be the command?

**Comment by matklad** [comment]
@Joe23232 i appreciate you interest in the crate, but note that this is a whole bunch of questions, and answering them all takes time. Many of them can be answered by reading more about the project (Cargo.toml, documentation, source code).

It makes more sense if this burden is carried by the users rather than maintainers — there’s way more users than maintainers, if each user asked 4 questions and I answered all of them, I’ll be answering question 24/7 without writing new code :)

**Comment by Joe23232** [comment]
Oh sorry mate lol.
