### ISSUE TITLE
Add Error::is_not_found or similar

### ISSUE THREAD

**Issue by jplatte** [matklad/xshell#46]
Use case: Some automation tools require other binaries to be installed. I would like to catch when that is not the case and print installation instructions.

**Comment by matklad** [comment]
SGTM!

Should probably add a `.kind()` method which returns a fieldless nonexhaustive enum.

**Comment by matklad** [comment]
Thinking about the broader problem, I think for myself I usually use the following pattern:

```rust
if cmd!(sh, "my-tool --version").run().is_err() {
    eprintln!("Install my tool");
    return
}
```

That is perhaps a better behavior than catching the error after-the-fact, because: 

* it's more transactional (we don't abort in the middle of the process)
* you also see a version of the tool printed to the screen, which helps with debugging issues when the tool exixsts, but it has wrong version (thinking about weird CI case mostly).

**Comment by matklad** [comment]
Revisiting, I lean towards not doing it:

* calling `tool --version` up-front is the right pattern to do this
* the error message xshell produces converts `FileNotFound` into `command not found` already

**Comment by jplatte** [comment]
Sorry for necro-posting, but can you elaborate on this?

> - calling `tool --version` up-front is the right pattern to do this

I don't see how it is in any way better than `Error::is_not_found`. It seems more verbose, less obvious and doesn't have exactly the same semantics. It also allows TOCTOU bugs, though I imagine that's not generally relevant in the type of program that would use xshell.

**Comment by matklad** [comment]
> calling tool --version up-front is the right pattern to do this

It requires some explicit code, but gives better UX than reacting to the error after the fact:

* Automation fails up-front, rather than down the line. This helps a lot if the job is long-running, and the tool is only needed at the end.
* Relatedly, automation fails cleanly, before any intermediate files are created.
* Printing version information on the success path is helpful to debug issues where the binary exists, but is the wrong one. 

The biggest problem here is that you'll have to add error handling, but, if you don't, you are still getting "command not found" message. I am actually not sure it'll end _more_ verbose than `is_not_found`? You'll need some explicit handling either way?
